CREATE TABLE ETL_000_00_WEB_MAPPER (
f1 VARCHAR(4000),
f2 VARCHAR(255) NULL,
f3 VARCHAR(255) NULL,
f4 VARCHAR(255) NULL,
f5 VARCHAR(255) NULL,
f6 VARCHAR(255) NULL,
f7 VARCHAR(255) NULL,
f8 VARCHAR(255) NULL,
f9 VARCHAR(255) NULL,
f10 VARCHAR(255) NULL,
f11 VARCHAR(255) NULL,
f12 VARCHAR(255) NULL,
f13 VARCHAR(255) NULL,
f14 VARCHAR(255) NULL,
f15 VARCHAR(255) NULL,
f16 VARCHAR(255) NULL,
f17 VARCHAR(255) NULL,
f18 VARCHAR(255) NULL,
f19 VARCHAR(255) NULL,
f20 VARCHAR(255) NULL
)

CREATE TABLE Ogol_000_00_CONFEDERACOES(
PK_CONFEDERACAO INT PRIMARY KEY,
DS_CONFEDERACAO_NOME VARCHAR(255) NULL
)

CREATE TABLE Ogol_001_00_PAISES(
PK_PAIS INT PRIMARY KEY,
FK_CONFEDERACAO INT,
DS_PAIS_NOME VARCHAR(255) NULL,

CONSTRAINT FK_CONFEDERACAO FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO)
)


CREATE TABLE Ogol_002_00_EQUIPES(
EQUIPE_CODIGO INT PRIMARY KEY,
COLETA_DATA DATETIME,
COLETA_HORA DATETIME,
EQUIPE_CONFEDERACAO_INDEX INT,
EQUIPE_PAIS_INDEX INT,
EQUIPE_WEBPAGE_INDEX VARCHAR(255), 
EQUIPE_ESTADO VARCHAR(255),
EQUIPE_CIDADE_CODIGO INT,
EQUIPE_CIDADE_NOME VARCHAR(255),
EQUIPE_NOME_ESPORTIVO VARCHAR(255),
EQUIPE_NOME_COMPLETO VARCHAR(255),
EQUIPE_FUNDACAO INT
)

CREATE TABLE Ogol_003_00_COMPETICOES(
PK_COMPETICAO INT PRIMARY KEY,
FK_CONFEDERACAO INT,
FK_PAIS INT,
DS_COMPETICAO_NOME VARCHAR(255) NULL,

CONSTRAINT FK_CONFEDERACAO_COMPETICOES FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_COMPETICOES FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS)
)

CREATE TABLE Ogol_004_00_EDICOES(
PK_EDICAO INT PRIMARY KEY,
FK_CONFEDERACAO INT,
FK_PAIS INT,
FK_COMPETICAO INT,
DS_EDICAO_TIMES INT,
DS_EDICAO_ANO INT,
DS_RODADAS INT,
DS_HABILITADO BOOLEAN,

CONSTRAINT FK_CONFEDERACAO_EDICOES FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_EDICOES FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS),
    
CONSTRAINT FK_COMPETICAO_EDICOES FOREIGN KEY (FK_COMPETICAO)
    REFERENCES Ogol_003_00_COMPETICOES(PK_COMPETICAO)
)

CREATE TABLE Ogol_005_00_CLASSIFICACOES(
PK_RODADA INT PRIMARY KEY,
COLETA_DATA DATETIME,
COLETA_HORA DATETIME,
FK_CONFEDERACAO INT,
FK_PAIS INT,
FK_COMPETICAO INT,
FK_CAMPEONATO INT,
FK_EDICAO INT,
FK_EQUIPE INT,

DS_CLASSIFICACAO INT,
DS_PONTOS INT,
DS_JOGOS INT,
DS_VITORIAS INT,
DS_EMPATES INT,
DS_DERROTAS INT,
DS_GOLS_PRO INT,
DS_GOLS_CONTRA INT,
DS_GOLS_SALDO INT,

CONSTRAINT FK_CONFEDERACAO_CLASSIFICACOES FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_CLASSIFICACOES FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS),
    
CONSTRAINT FK_COMPETICAO_CLASSIFICACOES FOREIGN KEY (FK_COMPETICAO)
    REFERENCES Ogol_003_00_COMPETICOES(PK_COMPETICAO),
    
CONSTRAINT FK_EDICAO_CLASSIFICACOES FOREIGN KEY (FK_EDICAO)
    REFERENCES Ogol_004_00_EDICOES(PK_EDICAO)
)


CREATE TABLE Ogol_006_00_PARTIDAS(
PK_PARTIDA INT PRIMARY KEY,

COLETA_DATA DATETIME,
COLETA_HORA DATETIME,

FK_CONFEDERACAO INT,
FK_PAIS INT,
FK_CAMPEONATO INT,
FK_EDICAO INT,
FK_EQUIPE INT,
FK_RODADA INT,

PARTIDA_DATA DATETIME,
PARTIDA_HORARIO DATETIME,

PARTIDA_EQUIPE_MANDANTE INT,
PARTIDA_EQUIPE_GOLS_PRO INT,
PARTIDA_EQUIPE_GOLS_CONTRA INT,
PARTIDA_EQUIPE_GOLS_SALDO INT,
PARTIDA_EQUIPE_STATUS VARCHAR(255),
PARTIDA_EQUIPE_PONTOS INT,
PARTIDA_EQUIPE_OPONENTE_CODIGO VARCHAR(255),

CONSTRAINT FK_CONFEDERACAO_PARTIDAS FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_PARTIDAS FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS),
    
CONSTRAINT FK_COMPETICAO_PARTIDAS FOREIGN KEY (FK_CAMPEONATO)
    REFERENCES Ogol_003_00_COMPETICOES(PK_COMPETICAO),
    
CONSTRAINT FK_EDICAO_PARTIDAS FOREIGN KEY (FK_EDICAO)
    REFERENCES Ogol_004_00_EDICOES(PK_EDICAO),
    
CONSTRAINT FK_RODADA_PARTIDAS FOREIGN KEY (FK_RODADA)
    REFERENCES Ogol_002_00_EQUIPES(PK_RODADA)
)

CREATE TABLE Ogol_007_00_PLANTEIS(
PK_JOGADOR INT PRIMARY KEY,

COLETA_DATA DATETIME,
COLETA_HORA DATETIME,

FK_CONFEDERACAO INT,
FK_PAIS INT,
FK_CAMPEONATO INT,
FK_EDICAO INT,
FK_EDICAO_PLANTEL INT,
FK_EQUIPE INT,

JOGADOR_NOME VARCHAR(255),
JOGADOR_IDADE INT,
JOGADOR_POSICAO VARCHAR(255),
EQUIPE_JOGADORES_TOTAL INT,

CONSTRAINT FK_CONFEDERACAO_PLANTEIS FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_PLANTEIS FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS),
    
CONSTRAINT FK_COMPETICAO_PLANTEIS FOREIGN KEY (FK_CAMPEONATO)
    REFERENCES Ogol_003_00_COMPETICOES(PK_COMPETICAO),
    
CONSTRAINT FK_EDICAO_PLANTEIS FOREIGN KEY (FK_EDICAO)
    REFERENCES Ogol_004_00_EDICOES(PK_EDICAO),
    
CONSTRAINT FK_EQUIPE_PLANTEIS FOREIGN KEY (FK_EQUIPE)
    REFERENCES Ogol_002_00_EQUIPES(EQUIPE_CODIGO)
)


CREATE TABLE Ogol_008_00_ESTATISTICAS_CONSOLIDADAS(
PK_JOGADOR INT PRIMARY KEY,

COLETA_DATA DATETIME,
COLETA_HORA DATETIME,

FK_CONFEDERACAO INT,
FK_PAIS INT,
FK_CAMPEONATO INT,
FK_EDICAO INT,
FK_EDICAO_PLANTEL INT,
FK_EQUIPE INT,

ESTATISTICAS_JOGADOR_JOGOS INT,
ESTATISTICAS_JOGADOR_VITORIAS INT,
ESTATISTICAS_JOGADOR_EMPATES INT,
ESTATISTICAS_JOGADOR_DERROTAS INT,
ESTATISTICAS_JOGADOR_MINUTOS_JOGADOS INT,
ESTATISTICAS_JOGADOR_SUBSTITUIDO INT,
ESTATISTICAS_JOGADOR_RESERVA_UTILIZADO INT,
ESTATISTICAS_JOGADOR_GOLS_MARCADOS INT,
ESTATISTICAS_JOGADOR_PRIMEIRO_AMARELOS INT,
ESTATISTICAS_JOGADOR_SEGUNDO_AMARELO INT,
ESTATISTICAS_JOGADOR_VERMELHO INT,

CONSTRAINT FK_CONFEDERACAO_ESTATISTICAS_CONSOLIDADAS FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_ESTATISTICAS_CONSOLIDADAS FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS),
    
CONSTRAINT FK_COMPETICAO_ESTATISTICAS_CONSOLIDADAS FOREIGN KEY (FK_CAMPEONATO)
    REFERENCES Ogol_003_00_COMPETICOES(PK_COMPETICAO),
    
CONSTRAINT FK_EDICAO_ESTATISTICAS_CONSOLIDADAS FOREIGN KEY (FK_EDICAO)
    REFERENCES Ogol_004_00_EDICOES(PK_EDICAO),
    
CONSTRAINT FK_EDICAO_PLANTEL_ESTATISTICAS_CONSOLIDADAS FOREIGN KEY (FK_EDICAO_PLANTEL)
    REFERENCES Ogol_007_00_PLANTEIS(PK_JOGADOR),
    
CONSTRAINT FK_EQUIPE_ESTATISTICAS_CONSOLIDADAS FOREIGN KEY (FK_EQUIPE)
    REFERENCES Ogol_002_00_EQUIPES(EQUIPE_CODIGO)
)


CREATE TABLE Ogol_008_01_ESTATISTICAS_JOGOS(
PK_JOGADOR INT PRIMARY KEY,

COLETA_DATA DATETIME,
COLETA_HORA DATETIME,

FK_CONFEDERACAO INT,
FK_PAIS INT,
FK_CAMPEONATO INT,
FK_EDICAO INT,
FK_EDICAO_PLANTEL INT,
FK_EQUIPE INT,

ESTATISTICA_JOGO_DATA DATETIME,
ESTATISTICA_JOGO_RODADA INT,
ESTATISTICA_JOGO_MINUTOS_EM_CAMPO INT,
ESTATISTICA_JOGOS_INICIO_PARTIDA VARCHAR(255),
ESTATISTICA_JOGOS_STATUS VARCHAR(255),
ESTATISTICA_CARTOES_AMARELOS VARCHAR(255),
ESTATISTICA_CARTOES_VERMELHOS VARCHAR(255),
ESTATISTICAS_GOLS_MARCADOS VARCHAR(255),

CONSTRAINT FK_CONFEDERACAO_ESTATISTICAS_JOGOS FOREIGN KEY (FK_CONFEDERACAO)
    REFERENCES Ogol_000_00_CONFEDERACOES(PK_CONFEDERACAO),
    
CONSTRAINT FK_PAIS_ESTATISTICAS_JOGOS FOREIGN KEY (FK_PAIS)
    REFERENCES Ogol_001_00_PAISES(PK_PAIS),
    
CONSTRAINT FK_COMPETICAO_ESTATISTICAS_JOGOS FOREIGN KEY (FK_CAMPEONATO)
    REFERENCES Ogol_003_00_COMPETICOES(PK_COMPETICAO),
    
CONSTRAINT FK_EDICAO_ESTATISTICAS_JOGOS FOREIGN KEY (FK_EDICAO)
    REFERENCES Ogol_004_00_EDICOES(PK_EDICAO),
    
CONSTRAINT FK_EDICAO_PLANTEL_ESTATISTICAS_JOGOS FOREIGN KEY (FK_EDICAO_PLANTEL)
    REFERENCES Ogol_007_00_PLANTEIS(PK_JOGADOR),
        
CONSTRAINT FK_EQUIPE_ESTATISTICAS_JOGOS FOREIGN KEY (FK_EQUIPE)
    REFERENCES Ogol_002_00_EQUIPES(EQUIPE_CODIGO)
)

SELECT * FROM Ogol_000_00_CONFEDERACOES